# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 046141712d467d4dedbf0d2af5a04a04bd638f29b2340ec4d148bc9764ff4c3abc1a4f907ae7f2d873f2e7be018034e198d173a6cd880cde0917380e73386df1

test:
  secret_key_base: 56f86c26af476ca9adaebe903d0cbf0d23e5fa10f4d6d87d1e2f0cd53538eef32c66be188cbd77fcde1809b3659e81b5907cc763908c0d6061aecaa96f0a3a08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
